spring:
  application:
    name: team2

  cloud:
    compatibility-verifier:
      enabled: false

  data:
    mongodb:
      uri: ${DB_URI:mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false}
      authentication-database: ${DB_AUTH:admin}
      database:  ${DB_NAME:taf}
      auto-index-creation: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    basename: validation
    encoding: ISO-8859-1

taf:
  app:
    jwtSecret: ${JWT_SECRET:bezKoderSecretKey}
    jwtExpirationMs: ${JWT_EXPIRES:86400000}
    testAPI_url:  ${TEST_API_SERVICE_URL:http://localhost}
    testAPI_port: ${TEST_API_SERVICE_PORT:8082}
    selenium_container_url: ${SELENIUM_URL:http://localhost}
    selenium_container_port: ${SELENIUM_PORT:8090}

server:
  port: 8085
  error:
    whitelabel:
      enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  #  prefer-ip-address: true

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:eureka}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    enabled: true
    path:  /swagger-ui.html

qa:
  reports-dir: target/cucumber-ui